apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: {{ include "frontend-label" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "frontend-label" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend-label" . }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontend.image.ports.port }}
