apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  labels:
    app: myapp
type: Opaque
data:
  DB_USER: {{ .Values.secrets.dbUser | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}

