apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: {{ include "frontend-label" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}
