ingress:
  host: ae17af75262a649ef97d437b2ae80270-525036724.us-east-1.elb.amazonaws.com
frontend:
  replicas: 2
  label: frontend
  image:
    repository: 015800953128.dkr.ecr.us-east-1.amazonaws.com/frontend
    tag: ""
    ports:
      port: 80
  service:
    type: ClusterIP
    targetPort: 80
    port: 80
