ingress:
  host: a02d89b7b24714d5d988cfb712dadbbd-1833324318.us-east-1.elb.amazonaws.com
frontend:
  replicas: 2
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend
    tag: latest
  service:
    type: ClusterIP
    port: 80
