ingress:
  host: a47214a85e8ae4ef6b15c1e8785bd139-2096017316.us-east-1.elb.amazonaws.com
frontend:
  replicas: 2
  label: frontend
  image:
    repository: 298334369719.dkr.ecr.us-east-1.amazonaws.com/frontend
    tag: ""
    ports:
      port: 80
  service:
    type: ClusterIP
    targetPort: 80
    port: 80
